Update fossa-scan.yml

diff --git a/.github/workflows/fossa-scan.yml b/.github/workflows/fossa-scan.yml
--- a/.github/workflows/fossa-scan.yml
+++ b/.github/workflows/fossa-scan.yml
@@ -34,6 +34,14 @@ jobs:
 
           echo "FOSSA_API_KEY=$FOSSA_API_KEY" >> "$GITHUB_ENV"
 
+      - name: Confirm var is set
+        run: |
+          if [ -z "$FOSSA_API_KEY" ]; then
+            echo "Missing FOSSA_API_KEY" && exit 1
+          else
+            echo "FOSSA_API_KEY is present"
+          fi
+
       - name: Run FOSSA Analysis
         run: |
           curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
